public without sharing class Constants{

    // General
    public static final string SEND_EVALUATION_REPORT = 'Send Evaluation Report';
    public static final string SEND_AGREEMENT_DOC ='Send Agreement Doc';

    // queue name
    public static final string PRIVATE_LEAD_QUEUE = 'Org Default Queue';
    public static final string PUBLIC_LEAD_QUEUE = 'App India Registration Queue';
    public static final string DISQUALIFIED_lEAD_QUEUE = 'Disqualified Lead Queue';



    // Lead Status 
    public static final string LEAD_STATUS_NEW ='New'; 
    public static final string LEAD_STATUS_CONTACTED = 'Contacted';
    public static final string LEAD_STATUS_UNDER_REGISTRATION = 'Under Registration';
    public static final string LEAD_STATUS_UNDER_JUNK = 'junk';
    

    // Lead SubStatus
    public static final string LEAD_SUBSTATUS_FOLLOWUP ='Follow up';
    public static final string LEAD_SUBSTATUS_CONNECTED= 'Connected';
    public static final string LEAD_SUBSTATUS_PRICE_TOO_HIGH = 'Price To High';
    public static final string LEAD_SUBSTATUS_CALLED = 'Called';
    public static final string LEAD_SUBSTATUS_NOT_ELIGIBLE = 'Not Eligible';
    public static final string LEAD_SUBSTATUS_NOT_INTERESTED = 'Not Interested';
    
    public static final string LEAD_Answered_Status_NOT_INTERESTED = 'Not Interested';
    
    //Invoice 

    public static final string INVOICE_REALIZED = 'Realized';

    // ==================================== Opportunity Stage ============================== 

    

}